apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: product-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: 3002
  selector:
    app: product-service
