apiVersion: v1
kind: Service                                                                                                                                                         
metadata:
  namespace: demo
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: order-service