apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: store-front
  labels:
    app: store-front
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: store-front
  type: ClusterIP
